### ISSUE TITLE
Deneb Upgrade and Clean Up

### ISSUE THREAD

**Issue by avalonche** [flashbots/mev-boost-relay#489]
# Task Tracking

Issue tracking for the Deneb Fork Upgrade and code clean up for mev-boost-relay. Changes tracked in the [`develop`](https://github.com/flashbots/mev-boost-relay/tree/develop) branch, NOT to be used for mainnet.

## Clean Up

**Removing wrapper types**

In `/common/types.go`:
* [x] Remove `SignedBlindedBeaconBlock` wrapper type https://github.com/flashbots/mev-boost-relay/pull/482
* [x] Remove `SignedBeaconBlock` wrapper type https://github.com/flashbots/mev-boost-relay/pull/483
* [x] Remove `VersionedExecutionPayload` wrapper type https://github.com/flashbots/mev-boost-relay/pull/475
* [x] Remove `BuilderSubmitBlockRequest` wrapper type https://github.com/flashbots/mev-boost-relay/pull/485
* [x] Remove `GetHeaderResponse` wrapper type https://github.com/flashbots/mev-boost-relay/pull/477

**Migrating to attestant types**

* [x]  Upgrade `go-boost-utils`
* [ ] Consistency across conflicting package names (see [here](https://github.com/flashbots/mev-boost-relay/pull/488#discussion_r1277903391))

## Deneb
* [x] Clean up deprecated forks and add Deneb fork versions https://github.com/flashbots/mev-boost-relay/pull/486
* [ ] Update `DomainBeaconProposer` and signatures with Deneb support 
* [ ] Consolidate the type conversion functions in `common/types_spec.go`
* [ ] Update `common/types_spec.go` with Deneb types and conversion to blinded blob bundles
* [ ] Refactor `VersionedSubmitBlockRequest` with custom marshalling and unmashalling
* [ ] Update marshalling for `BuilderBlockValidationRequest` and `flashbots_validateBuilderSubmissionV2` jsonrpc request to handle Deneb 
* [ ] Refactor `SignedBeaconBlock` and `SignedBlindedBeaconBlock` with custom marshalling and unmarshalling as the http requests do not have the `version` field
* [ ] Add `Eth-Consensus-Version` header to publishBlock endpoint
* [ ] Update `handleGetHeader`, `handleGetPayload` and `handleSubmitBlock` to handle Deneb types
* [ ] Update `payload_attributes` with `parentBeaconBlockRoot` 

## Dependencies

mev-boost-relay depends on the following changes and they are all still in branch form and / or not implemented yet. `go.mod` will need to be updated after the PRs are merged to upstream and point to the latest dependency.

### go-eth2-client
- Add `SignedBlockContents` types for Deneb `publishBlockV2` endpoint
- `VersionedSignedBlockContents` and `VersionedSignedBlindedBlockContents` types

### go-builder-client
- Fixing the ssz encoding for blob bundles https://github.com/attestantio/go-builder-client/pull/18
- Adding the builder bid structs to attestant https://github.com/attestantio/go-builder-client/pull/17
- Adding Deneb to the versioned struct for the signed header bid https://github.com/avalonche/go-builder-client/pull/1 
  - The base needs to be changed after https://github.com/attestantio/go-builder-client/pull/17 is merged
- `VersionedSubmitBlockRequest` types https://github.com/attestantio/go-builder-client/pull/15

### go-boost-utils
- Util functions to calculate the block hash and conversions https://github.com/flashbots/go-boost-utils/pull/87 
   - Will need to replace https://github.com/MariusVanDerWijden/go-ethereum/tree/4844-devnet-6 with latest geth release after the changes are merged
